# Generated by Django 5.1.4 on 2025-01-10 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_centro"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Centro",
        ),
    ]
