# Generated by Django 5.1.4 on 2025-01-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Centro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lugar", models.CharField(max_length=30)),
                ("numero", models.IntegerField()),
            ],
        ),
    ]
